klive epg를 사용자가 설정한 주소에서 가져오도록

diff --git a/root_epgkr/usr/bin/tv_grab_klive b/root_epgkr/usr/bin/tv_grab_klive
--- a/root_epgkr/usr/bin/tv_grab_klive
+++ b/root_epgkr/usr/bin/tv_grab_klive
@@ -1,55 +1,36 @@
 #!/bin/sh
-# tv_grab_file for remote XMLTV file
-dflag=
-vflag=
-cflag=
-if [ $# = 0 ]
-then
-    wget -q -O /epg2xml/klive.xml https://soju6jan.github.io/klive.xml
-    cat /epg2xml/klive.xml
-    exit 0
-fi
+# tv_grab_file for getting your own xmltv
+DESC="KLIVE EPG GRABBER"
+VER="1.1"
+CAP="baseline"
 
 for arg
 do
     delim=""
     case "$arg" in
     #translate --gnu-long-options to -g (short options)
-       --description) args="${args}-d ";;
-       --version) args="${args}-v ";;
-       --capabilities) args="${args}-c ";;
+       --description) printf "%s\n" "$DESC";;
+       --version) printf "%s\n" "$VER";;
+       --capabilities) printf "%s\n" "$CAP";;
+       -d) shift;;
        #pass through anything else
-       *) [[ "${arg:0:1}" == "-" ]] || delim="\""
-           args="${args}${delim}${arg}${delim} ";;
+       *) args="${args} ${arg}";;
     esac
 done
 
-eval set -- $args
-
-while getopts "dvc" option
-do
-    case $option in
-        d)  dflag=1;;
-        v)  vflag=1;;
-        c)  cflag=1;;
-        \?) printf "unknown option: -%s\n" $OPTARG
-            printf "Usage: %s: [--description] [--version] [--capabilities] \n" $(basename $0)
-            exit 2
-            ;;
-    esac >&2
-done
-
-if [ "$dflag" ]
-then
-   printf "KLIVE EPG GRABBER"
+if [ -z "$args" ]; then
+    exit 0
 fi
-if [ "$vflag" ]
-then
-   printf "1.0\n"
-fi
-if [ "$cflag" ]
-then
-   printf "baseline\n"
+
+args="${args:1:${#args}}"
+
+wget -q -O /epg2xml/klive.xml "${args}"
+if [ $? -ne 0 ]; then
+  echo "ERROR: Invalid download url for xmltv"
+  echo "ERROR: ${args}"
+  exit 2
+else
+  cat /epg2xml/klive.xml
 fi
 
 exit 0
